export const bikeStations = [
    {
        "Time":"2022-09-03 18:05:36",
        "DateTime":"2015/02/01",
        "Type": "Frequency test",
        "pass_rate": 14,
        "result": true,
        "Light":"Null",
    },
    {
        "Time":"2022-09-03 18:10:20",
        "DateTime":"2015/02/01",
        "Type": "Block Frequency test",
        "pass_rate": 40,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "3",
        "DateTime":"2015/02/11",
        "Type": "Longest Run Of Ones test",
        "pass_rate": 17,
        "result": true,
        "Light":"Null",
    },
    {
        "ID": "4",
        "DateTime":"2015/02/01",
        "Type": "Runs test",
        "pass_rate": 17,
        "result": true,
        "Light":"Null",
    },
    {
        "ID": "5",
        "DateTime":"2015/02/01",
        "Type": "Discrete Fourier Transform test",
        "pass_rate": 17,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "6",
        "DateTime":"2015/02/01",
        "Type": "Non-Overlapping Template Matchings test",
        "pass_rate": 17,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "7",
        "DateTime":"2015/02/01",
        "Type": "Overlapping Template Matchings test",
        "num_bikes_disabled": 2,
        "pass_rate": 30,
        "result": true,
        "Light":"Null",
    }, {
        "ID": "8",
        "DateTime":"2015/02/05",
        "Type": "Longest Run Of Ones test",
        "pass_rate": 70,
        "result": true,
        "Light":"Null",
    },
    {
        "ID": "9",
        "DateTime":"2015/02/01",
        "Type": "Matrix Rank test",
        "pass_rate": 40,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "10",
        "DateTime":"2015/02/01",
        "Type": "Universal test",
        "pass_rate": 40,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "11",
        "DateTime":"2015/02/01",
        "Type": "Matrix Rank test",
        "pass_rate": 25,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "12",
        "DateTime":"2015/02/01",
        "Type": "Linear Complexity test",
        "pass_rate": 30,
        "result": true,
        "Light":"Null",
    },
    {
        "ID": "13",
        "DateTime":"2015/02/01",
        "Type": "Approximate Entropy test",
        "pass_rate": 26,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "14",
        "DateTime":"2015/02/01",
        "Type": "Cumulative Sums test",
        "pass_rate": 5,
        "result": false,
        "Light":"Null",
    },
    {
        "ID": "15",
        "DateTime":"2015/02/01",
        "Type": "Random Excursions test",
        "pass_rate": 5,
        "result": true,
        "Light":"Null",
    },
    {
        "ID": "16",
        "DateTime":"2015/02/01",
        "Type": "randomExcursionsVariant test",
        "pass_rate": 40,
        "result": true,
        "Light":"Null",
    }
];